# Generated by Django 4.0.1 on 2022-01-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_pais_estado_cidade_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
